// Generated by https://quicktype.io

export interface SuccessCreatedFacilityContactDto {
    message:       string;
    createdEntity: {
        facilityCode:  string;
        contactPerson: string;
        catchmentArea: string;
    };
}
